### ISSUE TITLE
unable to do pip installation as per the description. 

### ISSUE THREAD

**Issue by engrsriram** [Soluto/spark-submit-with-pyspark-template#2]
`pip install -r ./requirements.txt -t ./pip_modules && jar -cvf pip_modules.jar -C ./pip_modules . jar -cvf src.jar -C ./src .`

didn't work as expected. 
showing error as : 

`Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
`

**Comment by AmirPupko** [comment]
Hi, I just gave it a try and it seems to work for me (I wasn't able to reproduce your error).
my env:
emr-5.10.0
pip 9.0.3

In addition there was a small change where the line you run was splitted into 2 lines (instead of 1) - I don't think it's the problem but worth trying...
It might be related to pip version..

**Comment by AmirPupko** [comment]
Closing issue for now
